default_stages:
  - commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: ./scripts/run-clang-tidy.sh
        language: system
        exclude: ^$
        pass_filenames: false
        stages:
          - commit
        types_or: [c++, c]

      - id: clang-format
        name: clang-format
        entry: clang-format --Werror --style=file -i --verbose
        exclude: ^$
        files: ""
        language: system
        pass_filenames: true
        stages:
          - commit
        types_or: [c++, c]

      - id: cppcheck
        name: cppcheck
        entry: "cppcheck --std=c++17 mpeepdf/"
        language: system
        pass_filenames: false
        stages:
          - commit
        types_or: [c++, c]
