name: poc-pdfmm
channels:
- nodefaults
- conda-forge
dependencies:
# build
- compilers
- compiler-rt
- clangdev 14.*
- clangxx 14.*
- cmake
- lld 14.*
- meson
- ninja
- pkg-config
# run
- cli11
- fmt 8.*
- glog
- opensciencelabs::pdfmm
- python
# dev
- include-what-you-use >=0.18
- cppcheck
- doxygen
- gmock
- gtest
- lcov
- nodejs
- pre-commit
